global:
  resolve_timeout: 1m

route:
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: [YourGmail@gmail.com]
        from: [YourGmail@gmail.com]
        smarthost: smtp.gmail.com:587
        auth_username: [YourGmail@gmail.com]
        auth_identity: [YourGmail@gmail.com]
        auth_password: [YourGoogleAppPassword] # https://support.google.com/accounts/answer/185833?hl=en
        send_resolved: true
