version: '3.8'

services:
  haproxy-master-slave:
    image: haproxy:2.4
    depends_on:
      - 'slave-node-2-ro'
    volumes:
      - ./haproxy/config:/usr/local/etc/haproxy:ro
    ports:
      - '3306:3306'  # Read-Write
      - '3307:3307'  # Read-Only

  master-node-1-rw:
    image: mariadb:10.4
    volumes:
      - ./mariadb/config/master:/etc/mysql/mariadb.conf.d
      - ./mariadb/sql/master:/docker-entrypoint-initdb.d
    ports:
      - '3308:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Asia/Seoul

  slave-node-1-ro:
    image: mariadb:10.4
    depends_on:
      - 'master-node-1-rw'
    volumes:
      - ./mariadb/config/slave-1:/etc/mysql/mariadb.conf.d
      - ./mariadb/sql/slave-1:/docker-entrypoint-initdb.d
    ports:
      - '3309:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Asia/Seoul

  slave-node-2-ro:
    image: mariadb:10.4
    depends_on:
      - 'master-node-1-rw'
    volumes:
      - ./mariadb/config/slave-2:/etc/mysql/mariadb.conf.d
      - ./mariadb/sql/slave-2:/docker-entrypoint-initdb.d
    ports:
      - '3310:3306'
    expose:
      - '4444'
      - '4568'
      - '4567'
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ=Asia/Seoul