version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.zen.minimum_master_nodes=2
      - network.bind_host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - node.master=true
      - node.data=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.zen.minimum_master_nodes=2
      - node.master=true
      - node.data=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.zen.minimum_master_nodes=2
      - node.master=true
      - node.data=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es-data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es-data01
    environment:
      - cluster.name=es-cluster
      - node.name=es-data01
      - node.master=false
      - node.data=true
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es-data02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es-data02
    environment:
      - cluster.name=es-cluster
      - node.name=es-data02
      - node.master=false
      - node.data=true
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es-data03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: es-data03
    environment:
      - cluster.name=es-cluster
      - node.name=es-data03
      - node.master=false
      - node.data=true
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    #environment:
      #SERVER_NAME: kibana
      #ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elastic
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.8
    container_name: logstash
    volumes:
      - type: bind
        source: "./docker/logstash/config/logstash.yml"
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: "./docker/logstash/config/pipelines.yml"
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
      - type: bind
        source: "./docker/logstash/pipeline"
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: "./docker/logstash//libs/mysql-connector-java-8.0.29.jar"
        target: /usr/share/logstash/jar/mysql-connector-java-8.0.29.jar
        read_only: true
    ports:
      - "5044:5044"
      - "5045:5045"
      - "5001:5001/tcp"
      - "5001:5001/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elastic
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - elastic
  elasticsearch_exporter:
    container_name: elasticsearch_exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
      - '--es.uri=http://es01:9200'
    restart: always
    ports:
      - "9114:9114"
    networks:
      - elastic
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    networks:
      - elastic
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: passwd
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
