global:
  scrape_interval:     15s
  evaluation_interval: 15s

#rule_files:
#  - rules.yml

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets: ['host.docker.internal:9093']

scrape_configs:
  - job_name: 'spring boot scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'elasticsearch scrape'
    scrape_interval: 45s
    scrape_timeout:  30s
    metrics_path: "/metrics"
    static_configs:
      - targets:
      - targets: ['host.docker.internal:9114']
