spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

mariadb:
  routing-datasource:
    shards:
      - groupId: 1
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: passwd
        master:
          name: default-master
          url: jdbc:mariadb://localhost:3306/defaultdb
        slaves:
          - name: default-slave-1
            url: jdbc:mariadb://localhost:3307/defaultdb
          - name: default-slave-2
            url: jdbc:mariadb://localhost:3308/defaultdb
      - groupId: 1
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: passwd
        master:
          name: business-master
          url: jdbc:mariadb://localhost:3309/businessdb
        slaves:
          - name: business-slave-1
            url: jdbc:mariadb://localhost:3310/businessdb
          - name: business-slave-2
            url: jdbc:mariadb://localhost:3311/businessdb
      - groupId: 2
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: passwd
        master:
          name: business-master
          url: jdbc:mariadb://localhost:3312/businessdb
        slaves:
          - name: business-slave-1
            url: jdbc:mariadb://localhost:3313/businessdb
          - name: business-slave-2
            url: jdbc:mariadb://localhost:3314/businessdb
    sharding:
      strategy: RANGE
      rules:
        - shard_no: 1
          range_min: 0
          range_max: 10
        - shard_no: 2
          range_min: 11
          range_max: 9223372036854775807