spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
mariadb:
  routing-datasource:
    read-write:
      url: jdbc:mariadb://localhost:3306/test-db
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: passwd
    read-only:
      url: jdbc:mariadb://localhost:3307/test-db
      driverClassName: org.mariadb.jdbc.Driver
      username: root
      password: passwd

dgs:
  graphql:
    graphiql:
      enabled: true
