spring:
  datasource:
    master:
      jdbc-url: jdbc:mariadb://localhost:3306/queryoffloading
      username: root
      password: passwd
      driver-class-name: org.mariadb.jdbc.Driver
    slave:
      jdbc-url: jdbc:mariadb://localhost:3307/queryoffloading
      username: root
      password: passwd
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate.SQL: info
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
