version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: passwd
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./etc/prometheus/rules.yml:/etc/prometheus/rules.yml:ro
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    restart: always
    ports:
      - 9093:9093
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - prometheus
  loki:
    image: grafana/loki:latest
    ports:
      - 3100:3100
    volumes:
      - ./etc/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml
  application:
    image: kwj1270/kotlin-monitoring:latest
    depends_on:
      - kafka
      - redis
    ports:
      - 8080:8080
  promtail:
    depends_on:
      - kafka
    image: grafana/promtail:latest
    depends_on:
      - kafka
      - loki
      - application
    volumes:
      - ./etc/promtail/config.yml:/etc/promtail/config.yml:ro
  influxdb:
    image: influxdb:1.8
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin1234
  k6:
    image: grafana/k6:latest
    ports:
      - 6565:6565
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./etc/k6/scripts:/scripts
    entrypoint: sh -c "k6 run /scripts/loadTest.js"
networks:
  monitoring:
    driver: bridge
