server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: kafka
    kafka:
      use_incoming_timestamp: false
      brokers:
        - kafka:9092
      group_id: some_group
      topics:
        - app-log
      labels:
        job: kafka
    relabel_configs:
      - action: replace
        source_labels:
          - __meta_kafka_topic
        target_label: topic
      - action: replace
        source_labels:
          - __meta_kafka_partition
        target_label: partition
      - action: replace
        source_labels:
          - __meta_kafka_group_id
        target_label: group
  - job_name: spring log
    static_configs:
      - targets:
          - host.docker.internal
        labels:
          job: spring logs
          __path__: /var/log/*log